### ISSUE TITLE
numInputPlane = nOutputPlane

### ISSUE THREAD

**Issue by davidBelanger** [jhjin/flattened-cnn#2]
I'm confused by the restriction that the number of output channels must equal the number of input channels. What's the rationale for this restriction? Is there a way for me to get around it?

**Comment by jhjin** [comment]
@davidBelanger for horizontal and vertical convolutions, what I intended is that one-to-one convolution mapping, which does not mix any information between feature maps. Otherwise, it becomes functionally the same as `nn.SpatialConvolutionMM` with filter size of `1 x n` or `n x 1`.

**Comment by davidBelanger** [comment]
Thanks for the info! It sounds like I should use nn.SpatialConvolutionMM for
my problem.
Cheers,
David
